name: votes
services:
    votes_backend:
        image: votes_backend
        container_name: votes_backend
        depends_on:
          - db
        build:
            context: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/:/voting_backend/
        environment:
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
    db:
      image: mysql
      build:
        context: ./db
      ports:
        - 3306:3306
      volumes:
        - mysql_data:/var/lib/mysql
        - ./db/init:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql_data:
