// auto-generated by sqlc - do not edit
using System;
using System.Collections.Generic;

namespace backend.src.Queries.Codegen;

public readonly record struct Author(long Id, string Name, string? Bio);
