// auto-generated by sqlc - do not edit
// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable UseAwaitUsing
// ReSharper disable ConvertToUsingDeclaration
// ReSharper disable NotAccessedPositionalProperty.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.TypeConversion;
using MySqlConnector;

namespace backend.src.Queries.Codegen;

public class QueriesSql
{
    public QueriesSql(string connectionString)
    {
        this.ConnectionString = connectionString;
    }

    private string ConnectionString { get; }

    private const string GetCitizenSql =
        "SELECT citizen_id, uruguayan_id, credencial_civica, name, surname, birth, password_hash FROM  citizen  WHERE  uruguayan_id  =  @uruguayan_id  ";

    public readonly record struct GetCitizenRow(
        string CitizenId,
        long UruguayanId,
        long CredencialCivica,
        string Name,
        string Surname,
        DateTime Birth,
        string PasswordHash
    );

    public readonly record struct GetCitizenArgs(long UruguayanId);

    public async Task<GetCitizenRow?> GetCitizen(GetCitizenArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetCitizenSql, connection))
            {
                command.Parameters.AddWithValue(
                    "@uruguayan_id",
                    args.UruguayanId
                );
                using (var reader = await command.ExecuteReaderAsync())
                {
                    if (await reader.ReadAsync())
                    {
                        return new GetCitizenRow
                        {
                            CitizenId = reader.GetString(0),
                            UruguayanId = reader.GetInt64(1),
                            CredencialCivica = reader.GetInt64(2),
                            Name = reader.GetString(3),
                            Surname = reader.GetString(4),
                            Birth = reader.GetDateTime(5),
                            PasswordHash = reader.GetString(6),
                        };
                    }
                }
            }
        }

        return null;
    }
}
