// auto-generated by sqlc - do not edit
using System.Linq;

namespace backend.src.Queries.Codegen;

public static class Utils
{
    public static string TransformQueryForSliceArgs(
        string originalSql,
        int sliceSize,
        string paramName
    )
    {
        var paramArgs = Enumerable.Range(0, sliceSize).Select(i => $"@{paramName}Arg{i}").ToList();
        return originalSql.Replace(
            $"/*SLICE:{paramName}*/@{paramName}",
            string.Join(",", paramArgs)
        );
    }
}
